// seeder/seeding/seedAuditLog.js
export async function up(queryInterface) {
  // Audit log entries are generated by the application
  // No seed data needed
}

export async function down(queryInterface) {
  await queryInterface.bulkDelete('audit_log', null, {});
}