// seeder/seeding/seedClassification.js
export async function up(queryInterface) {
  // Classifications are generated by the classification engine
  // No seed data needed
}

export async function down(queryInterface) {
  await queryInterface.bulkDelete('classifications', null, {});
}